# Generated by Django 5.1.1 on 2024-09-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantacion_cards_p_e', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardpe',
            name='urlDestino',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
