# Generated by Django 5.1.1 on 2024-09-26 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consejos_para_su_cultivo', '0002_etapa_decripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etapa',
            name='decripcion',
        ),
    ]
