# Generated by Django 5.1.1 on 2024-09-24 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consejos_para_su_cultivo', '0003_alter_etapa_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapa',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
