# Generated by Django 5.1.1 on 2024-09-24 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consejos_para_su_cultivo', '0004_alter_etapa_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etapa',
            name='descripcion',
        ),
    ]
