# Generated by Django 5.1.1 on 2024-09-11 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etapa_plagas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='etapas_plagas',
            new_name='etapa',
        ),
    ]
