# Generated by Django 5.1.1 on 2024-09-12 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etapa_plagas', '0002_rename_etapas_plagas_etapa'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapa',
            name='urlDestino',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
