# Generated by Django 5.1.1 on 2024-09-12 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_inicial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='urlDestino',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
