# Generated by Django 5.1.1 on 2024-09-27 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_inicial', '0002_modulo_urldestino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulo',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
