# Generated by Django 5.1.1 on 2024-09-11 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='enfermedades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=7)),
                ('descripcion', models.TextField()),
                ('sintomas', models.TextField()),
                ('tratamiento', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='modulos')),
            ],
        ),
        migrations.CreateModel(
            name='plagas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=7)),
                ('descripcion', models.TextField()),
                ('sintomas', models.TextField()),
                ('tratamiento', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='modulos')),
            ],
        ),
    ]
