# Generated by Django 5.1.1 on 2024-09-12 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etapa_de_plantacion_plagas_enfermedades', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='enfermedades',
            new_name='enfermedade',
        ),
        migrations.RenameModel(
            old_name='plagas',
            new_name='plaga',
        ),
    ]
