# Generated by Django 5.1.1 on 2024-09-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broca', '0002_broca_sintomas2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broca',
            name='sintomas2',
            field=models.TextField(default=0),
        ),
    ]
