# Generated by Django 5.1.1 on 2024-09-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broca', '0003_alter_broca_sintomas2'),
    ]

    operations = [
        migrations.AddField(
            model_name='broca',
            name='sintomas3',
            field=models.TextField(default=0),
        ),
    ]
