# Generated by Django 5.1.1 on 2024-09-27 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plagas_y_enfermedades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='modulos')),
                ('urlDestino', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='etapas_plagas',
        ),
    ]
