# Generated by Django 5.1.1 on 2024-09-17 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etapa_elecion_semilla', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='variedades_info',
            new_name='variedade_info',
        ),
    ]
