# Generated by Django 5.1.1 on 2024-09-25 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpc_etapa_de_siembra', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='variedade_info',
            new_name='etapa_de_siembra',
        ),
    ]
