# Generated by Django 5.1.1 on 2024-09-25 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpc_etapa_de_siembra', '0002_rename_variedade_info_etapa_de_siembra'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='etapa_de_siembra',
            new_name='etapa',
        ),
    ]
