# Generated by Django 5.1.1 on 2024-09-26 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpc_etapa_de_siembra', '0003_rename_etapa_de_siembra_etapa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapa',
            name='a_tener_en_cuenta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='etapa',
            name='a_tener_en_cuenta2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='etapa',
            name='a_tener_en_cuenta3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
